title: Sudhrity Mondal
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sudhrity.github.io" # the base hostname & protocol for your site
author: "Sudhrity Mondal"
email: "sudhrity@gmail.com"
logo: /assets/img/headshot_circle.png
description: 'Some description
    
  <a href="https://www.linkedin.com/in/sudhrity/">View my Linkedin profile</a>'
show_downloads: true
theme: jekyll-theme-minimal
