title: Sudhrity Mondal
logo: /assets/img/headshot_circle.png
description: Some description \n
\n
<a href="https://www.linkedin.com/in/sudhrity/">View my Linkedin profile</a>\n
show_downloads: true
theme: jekyll-theme-minimal
