title: Sudhrity Mondal
logo: /assets/img/headshot_circle.png
description: > 
  Some description test1
  <br>
  <br>  
  <a href="https://www.linkedin.com/in/sudhrity/">View My Linkedin Profile</a>
show_downloads: true
theme: jekyll-theme-minimal

